name: CI/CD
on: push

jobs:
  linux1:
    name: Produce a .pdf.gz version for pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: install requirements
      run: sudo make install
    - name: Build a .pdf file
      run: make
    - name: Add cname to the directory
      uses: hapytex/github-actions/actions/add-cname-to-directory@master
      with:
        folder: out
        cname: "unicode.django-antipatterns.com"
    - name: deploy the .pdf.gz document
      uses: JamesIves/github-pages-deploy-action@v4.3.4
      with:
        branch: gh-pages
        folder: out
        single-commit: true
